In [1]:
# Numpy assignment
# Q1 Create a 5X2 integer array from a range between 100 to
# 200 such that the difference between each element is 10
import numpy

print("5X2 Array")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)


5X2 Array
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [2]:
#Q2 Write a NumPy program to create a 3x3x3 array filled
# with arbitrary values and find the minimum and maximum values.
import numpy as np
x = np.random.random((3, 3, 3))
print(x)
xmin, xmax = x.min(), x.max()
print("Minimum Value", xmin)
print("Maximum Value", xmax)


[[[0.53978016 0.95036163 0.84614015]
  [0.70671011 0.51115981 0.66709128]
  [0.14956464 0.15763464 0.45537978]]

 [[0.12124375 0.03022605 0.11056695]
  [0.06667052 0.22783834 0.64429077]
  [0.28506238 0.62556291 0.98494633]]

 [[0.63851742 0.13843682 0.57290376]
  [0.42423843 0.72870984 0.96601091]
  [0.2586395  0.96994003 0.5475506 ]]]
Minimum Value 0.03022605100244713
Maximum Value 0.98494633063145


In [3]:
#Q3 Write a NumPy program to create a 5x5 zero matrix
# with elements on the main diagonal equal to 1, 2, 3, 4, 5.
import numpy

Z = np.diag(1+np.arange(5),k=0)
print(Z)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
#Q4 Given an array: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9
# i) Extract all odd numbers from arr
# ii) Replace all odd numbers in arr with -1
#i)
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]


array([1, 3, 5, 7, 9])

In [5]:
#Q4 ii)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
#Q5 Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#Q6 Write a NumPy program to convert an array to a floattype.
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [8]:
#Q7 Write a NumPy program to generate five random numbers from the normal distribution.
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.78054038 -0.02746958 -0.85089124 -0.39050084 -0.09936346]


In [9]:
#Q8 Following is the input NumPy array delete column two
# and insert following new column in its place.
# sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,66]])
# newColumn = numpy.array([[10,10,10]])
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)


Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [10]:
# Q9 Write a NumPy program to compute the multiplication of two given matrices.
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)


original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


In [11]:
# Q10 Write a NumPy program to create a random vector ofsize 10 and sort it.
Z = np.random.random(10)
print(Z)
Z.sort()
print(Z)

[0.44684873 0.0489885  0.58786079 0.07966657 0.74794113 0.28762148
 0.01266941 0.14055544 0.98218536 0.3046687 ]
[0.01266941 0.0489885  0.07966657 0.14055544 0.28762148 0.3046687
 0.44684873 0.58786079 0.74794113 0.98218536]


In [12]:
# Q11 Write a NumPy program to compute the covariance matrix of two arrays.
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array2:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array2:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [13]:
# Q12 Create a 4X2 integer array and Prints its :
# i)The shape of an array.
# ii) Array dimensions.
# iii) The Length of each element of the array in bytes
import numpy

firstArray = numpy.empty([4,2], dtype = numpy.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[    0     0]
 [    0 16368]
 [    0     0]
 [    0 16368]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


In [14]:
# Q13 Write a NumPy program to concatenate element-wise two arrays of string.
import numpy as np
x1 = np.array(['Python', 'PHP'], dtype=np.str)
x2 = np.array([' Java', ' C++'], dtype=np.str)
print("Array1:")
print(x1)
print("Array2:")
print(x2)
new_array = np.char.add(x1, x2)
print("new array:")
print(new_array)

Array1:
['Python' 'PHP']
Array2:
[' Java' ' C++']
new array:
['Python Java' 'PHP C++']


In [15]:
# Q14 Write a NumPy program to capitalize the first letter,
# lowercase, uppercase, swapcase, title-case of all the elements of a given array.
import numpy as np
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


In [16]:
# Q15 Write a NumPy program to convert a given array into a list.
import numpy as np

# 1d array to list
arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')

# 2d array to list
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f'NumPy 2d Array:\n{arr}')

list1 = arr.tolist()

print(f'List: {list1}')

NumPy Array:
[1 2 3]
List: [1, 2, 3]
NumPy 2d Array:
[[1 2 3]
 [4 5 6]]
List: [[1, 2, 3], [4, 5, 6]]


In [17]:
# Q16 Write a NumPy program to compute the sum of all
# elements, sum of each column and sum of each row of a given array.
import numpy as np
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [18]:
# Q17 Write a NumPy program to create a random 10x4
# array and extract the first five rows of the array and store
# them into a variable.
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.57052998 0.73380667 0.47539586 0.84430708]
 [0.13111295 0.89994717 0.40860626 0.99847708]
 [0.68607474 0.94664278 0.95054443 0.68459067]
 [0.96003217 0.91484553 0.44819631 0.35855956]
 [0.35887641 0.42991491 0.66161116 0.55569107]
 [0.52610639 0.88367453 0.60307586 0.21787873]
 [0.56060218 0.77362957 0.3946976  0.44262378]
 [0.32538874 0.36120569 0.71056147 0.21360497]
 [0.08484623 0.65737005 0.15981664 0.63134926]
 [0.94934115 0.53449431 0.42877714 0.72414224]]
First 5 rows of the above array:
[[0.57052998 0.73380667 0.47539586 0.84430708]
 [0.13111295 0.89994717 0.40860626 0.99847708]
 [0.68607474 0.94664278 0.95054443 0.68459067]
 [0.96003217 0.91484553 0.44819631 0.35855956]
 [0.35887641 0.42991491 0.66161116 0.55569107]]


In [19]:
# Q18 Write a NumPy program to get the unique elements of a 1D and 2D array.
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))
x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [20]:
#Q19 Write a NumPy program to get the unique elements of an array.
# arr= [ -10 12.12 -0.2]
x = np.array([-10 12.12 -0.2])
print("Original array:")
print(x)
print("Unique elements of the above array:")
print(np.unique(x))


SyntaxError: invalid syntax (<ipython-input-20-98fab79ae4a3>, line 3)

In [21]:
# Q20 Write a NumPy program to save a given array to a text
# file and load it. You have to save and load files using numpy library
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
